BaseDatosFisica/Controllers/EstudiantesController.cs
using BaseDatosFisica.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseDatosFisica.Controllers
{
    [Authorize]
    public class EstudiantesController : Controller
    {
        // GET: Estudiantes
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            if (!User.IsInRole("admin"))
                return Content("No tienes permisos de administrador");

            return View(db.Users.Where(m=>m.UserName != User.Identity.Name).ToList());
        }

        public ActionResult Delete(string idEstudiante)
        {
            if (idEstudiante == null)
                return Content("Error");

            var estudiante = db.Users.Find(idEstudiante);
            if (estudiante == null)
                return Content("Estudiante no encontrado");

            return View(estudiante);
        }

        
        public ActionResult DeleteConfirmed(string idEstudiante)
        {
            if (!User.IsInRole("admin"))
            {
                return Content("No tiene permisos de administrador");
            }

            var estudiante = db.Users.Find(idEstudiante);
            if (estudiante == null)
                return Content("Estudiante no encontrado");

            var testEstudiantes = estudiante.TestsEstudiante;
            db.TestsEstudiantes.RemoveRange(testEstudiantes);

            db.Users.Remove(estudiante);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

BaseDatosFisica/Views/Estudiantes/Delete.cshtml
@model BaseDatosFisica.Models.ApplicationUser
@{
    ViewBag.Title = "Delete";
}

<h2>Seguro que desea eliminar a @Model.Nombre @Model.Apellidos?</h2>

<table>
    <tr>
        <td>
            <a href="/Estudiantes/DeleteConfirmed?idEstudiante=@Model.Id" class="btn-default btn">Si</a> 
        </td>
        <td></td>
        <td></td>
        <td>|</td>
        <td></td>
        <td></td>
        


        <td>
            <a href="/Estudiantes/Index" class="btn-default btn">No</a>
        </td>
    </tr>
</table>

 

BaseDatosFisica/Views/Estudiantes/Edit.cshtml
@model BaseDatosFisica.Models.ApplicationUser
@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "Estudiantes", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Editar estudiante</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Nombre, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Apellidos, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Apellidos, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NumeroOpcion, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumeroOpcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumeroOpcion, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ProcedenciaID, "ProcedenciaID", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">

            @Html.DropDownList("ProcedenciaID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProcedenciaID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Promedio, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Promedio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Promedio, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Editar" />
        </div>
    </div>
}

BaseDatosFisica/Views/Estudiantes/Index.cshtml
@model IEnumerable<BaseDatosFisica.Models.ApplicationUser>
@{
    ViewBag.Title = "Estudiantes";
}

<h2>Estudiantes</h2>

<table class="table">
    <tr>
        <th>
            Nombre
        </th>
        <th>
            Promedio
        </th>
        <th>
            Número de Opción
        </th>
        <th>
            Procedencia
        </th>
        <th>
            Correo
        </th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
               @Html.ActionLink(item.Nombre + " " + item.Apellidos, "Calificaciones", "ResponderTest", new {idEstudiante = item.Id }, null)
            </td>
            
            <td>
                @item.Promedio
            </td>
            <td>
                @item.NumeroOpcion
            </td>
            <td>
                @item.procedencia.valor
            </td>
            <td>
                @item.Email
            </td>

           <td></td>
            <td></td>
            <td></td>
            <td>@Html.ActionLink("Editar", "Edit", new { idEstudiante = item.Id})</td>
            <td>@Html.ActionLink("Eliminar", "Delete", new { idEstudiante = item.Id })</td>

            </tr>
    }
</table>